/**
 * The wire format, as the compiler actually emits it.
 *
 * @generated by `cargo test -p trestle-wasm --test wire_format` — do not edit by hand.
 *
 * This file exists to be type-checked, not to be imported. Each fixture is a literal produced
 * by serialising a real `crates/trestle-wasm/src/dto.rs` value, annotated with the hand-written
 * type it is supposed to satisfy. If the two ever disagree — a renamed field, a changed
 * nullability, a new member — `pnpm typecheck` fails here, on the boundary itself, rather than
 * at runtime in a worker.
 */

import type { CheckResult, RunResult } from './types'

export const WIRE_FIXTURES: {
  checkOk: CheckResult
  checkFailed: CheckResult
  runOk: RunResult
  runFailed: RunResult
} = {
  checkOk: {
    "ok": true,
    "bindings": [
      {
        "name": "point",
        "type": "{ x: Int }",
        "startLine": 1,
        "startColumn": 1,
        "endLine": 1,
        "endColumn": 22
      }
    ]
  },
  checkFailed: {
    "ok": false,
    "diagnostics": [
      {
        "phase": "resolve",
        "severity": "error",
        "code": "trestle::duplicate_binding",
        "message": "`a` is already declared in this scope",
        "help": "rename one of them",
        "labels": [
          {
            "message": "redeclared here",
            "startLine": 1,
            "startColumn": 11,
            "endLine": 1,
            "endColumn": 16,
            "offset": 10,
            "length": 5
          },
          {
            "message": "first declared here",
            "startLine": 1,
            "startColumn": 1,
            "endLine": 1,
            "endColumn": 6,
            "offset": 0,
            "length": 5
          }
        ],
        "render": "  × `a` is already declared in this scope\n"
      },
      {
        "phase": "typecheck",
        "severity": "advice",
        "code": null,
        "message": "this annotation is redundant",
        "help": null,
        "labels": [
          {
            "message": null,
            "startLine": 1,
            "startColumn": 5,
            "endLine": 1,
            "endColumn": 8,
            "offset": 4,
            "length": 3
          }
        ],
        "render": "  ☞ this annotation is redundant\n"
      }
    ]
  },
  runOk: {
    "ok": true,
    "value": "{ x: 1 }",
    "valueType": "{ x: Int }",
    "bindings": [
      {
        "name": "point",
        "type": "{ x: Int }",
        "startLine": 1,
        "startColumn": 1,
        "endLine": 1,
        "endColumn": 22
      }
    ]
  },
  runFailed: {
    "ok": false,
    "diagnostics": [
      {
        "phase": "evaluate",
        "severity": "warning",
        "code": "trestle::division_by_zero",
        "message": "division by zero",
        "help": "the right-hand side of `/` evaluated to 0",
        "labels": [
          {
            "message": "this division has a zero divisor",
            "startLine": 1,
            "startColumn": 1,
            "endLine": 1,
            "endColumn": 6,
            "offset": 0,
            "length": 5
          }
        ],
        "render": "  × division by zero\n"
      }
    ]
  },
}
