//! Generates the wire-format fixtures the playground type-checks itself against.
//!
//! `crates/trestle-wasm/src/dto.rs` and `apps/demo/app/lib/compiler/types.ts` describe the same
//! objects in two languages, and there is no codegen step between them. Both files say "keep
//! these in step"; this test is what makes that more than a request.
//!
//! It builds one value of every shape that can cross the boundary, serialises them, and writes
//! them out as a TypeScript module whose object literals are annotated with the *hand-written*
//! types. Rename a field on the Rust side and `pnpm typecheck` fails on the fixture; rename it
//! on the TypeScript side and it fails the same way. CI additionally runs
//! `git diff --exit-code` on the generated file, so a change made in Rust and never mirrored
//! cannot ship.
//!
//! **Why `serde_json` is a fair stand-in for `serde-wasm-bindgen`.** Neither decides the shape:
//! the `#[serde]` attributes on the DTOs do — `rename_all = "camelCase"`, `rename = "type"` on
//! `Binding::ty`, `untagged` on the two result enums — and both serialisers read exactly those.
//! The one place they could differ is `None`, and they do not: `lib.rs::to_js` configures
//! `serialize_missing_as_null(true)` precisely so a `None` becomes an explicit `null` rather
//! than a missing key, which is what `serde_json` emits anyway. If that setting is ever
//! removed, these fixtures stop describing reality — so it is load-bearing, not decorative.

use std::fs;
use std::path::PathBuf;

use trestle_wasm::dto::{Binding, CheckResult, Diagnostic, Label, Phase, RunResult, Severity};

/// Relative to this crate, which `CARGO_MANIFEST_DIR` pins regardless of where cargo is run.
const FIXTURES: &str = "../../apps/demo/app/lib/compiler/wire-fixtures.ts";

#[test]
fn wire_fixtures_are_in_step_with_the_dtos() {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(FIXTURES);
    let generated = render_module();

    // Read before writing: the assertion below compares against what was committed, so the
    // test fails on drift rather than quietly correcting it. The file is still rewritten, so
    // the fix is `git add` — the same ergonomics as the `insta` snapshots in `crates/trestle`.
    let existing = fs::read_to_string(&path).unwrap_or_default();

    if existing != generated {
        fs::write(&path, &generated).expect("failed to write the wire-format fixtures");

        // Deliberately not `assert_eq!`: both sides are the whole file, and printing them
        // twice buries the one line that says what to do. `git diff` shows the change better
        // than a panic message can.
        panic!(
            "\n`apps/demo/app/lib/compiler/wire-fixtures.ts` was out of date and has been \
             rewritten.\nReview the diff, mirror any change into \
             `app/lib/compiler/types.ts`, and commit both.\n"
        );
    }
}

fn render_module() -> String {
    let fixtures = [
        ("checkOk", "CheckResult", json(&check_ok())),
        ("checkFailed", "CheckResult", json(&check_failed())),
        ("runOk", "RunResult", json(&run_ok())),
        ("runFailed", "RunResult", json(&run_failed())),
    ];

    let declared = fixtures
        .iter()
        .map(|(name, ty, _)| format!("  {name}: {ty}\n"))
        .collect::<String>();

    let values = fixtures
        .iter()
        .map(|(name, _, body)| format!("  {name}: {},\n", indent(body)))
        .collect::<String>();

    format!(
        "\
/**
 * The wire format, as the compiler actually emits it.
 *
 * @generated by `cargo test -p trestle-wasm --test wire_format` — do not edit by hand.
 *
 * This file exists to be type-checked, not to be imported. Each fixture is a literal produced
 * by serialising a real `crates/trestle-wasm/src/dto.rs` value, annotated with the hand-written
 * type it is supposed to satisfy. If the two ever disagree — a renamed field, a changed
 * nullability, a new member — `pnpm typecheck` fails here, on the boundary itself, rather than
 * at runtime in a worker.
 */

import type {{ CheckResult, RunResult }} from './types'

export const WIRE_FIXTURES: {{
{declared}}} = {{
{values}}}
"
    )
}

fn json<T: serde::Serialize>(value: &T) -> String {
    serde_json::to_string_pretty(value).expect("the DTOs are plain data and always serialise")
}

/// Re-indent a pretty-printed JSON block so it sits inside the object literal. The first line
/// is already positioned by the caller, so only the continuation lines move.
fn indent(body: &str) -> String {
    body.replace('\n', "\n  ")
}

fn check_ok() -> CheckResult {
    CheckResult::ok(vec![binding()])
}

fn check_failed() -> CheckResult {
    CheckResult::failed(vec![two_label_error(), advice()])
}

fn run_ok() -> RunResult {
    RunResult::ok(
        "{ x: 1 }".to_owned(),
        "{ x: Int }".to_owned(),
        vec![binding()],
    )
}

fn run_failed() -> RunResult {
    RunResult::failed(vec![warning()])
}

fn binding() -> Binding {
    Binding {
        name: "point".to_owned(),
        ty: "{ x: Int }".to_owned(),
        start_line: 1,
        start_column: 1,
        end_line: 1,
        end_column: 22,
    }
}

/// The interesting error shape: two labels (miette's `DuplicateBinding` has exactly this
/// form) and both optional fields present.
fn two_label_error() -> Diagnostic {
    Diagnostic {
        phase: Phase::Resolve,
        severity: Severity::Error,
        code: Some("trestle::duplicate_binding".to_owned()),
        message: "`a` is already declared in this scope".to_owned(),
        help: Some("rename one of them".to_owned()),
        labels: vec![
            label(Some("redeclared here"), 10, 5),
            label(Some("first declared here"), 0, 5),
        ],
        render: "  × `a` is already declared in this scope\n".to_owned(),
    }
}

/// The other end of the range: both optional fields absent, so the fixture pins that a `None`
/// crosses as `null` rather than as a missing key.
fn advice() -> Diagnostic {
    Diagnostic {
        phase: Phase::Typecheck,
        severity: Severity::Advice,
        code: None,
        message: "this annotation is redundant".to_owned(),
        help: None,
        labels: vec![label(None, 4, 3)],
        render: "  ☞ this annotation is redundant\n".to_owned(),
    }
}

fn warning() -> Diagnostic {
    Diagnostic {
        phase: Phase::Evaluate,
        severity: Severity::Warning,
        code: Some("trestle::division_by_zero".to_owned()),
        message: "division by zero".to_owned(),
        help: Some("the right-hand side of `/` evaluated to 0".to_owned()),
        labels: vec![label(Some("this division has a zero divisor"), 0, 5)],
        render: "  × division by zero\n".to_owned(),
    }
}

fn label(message: Option<&str>, offset: u32, length: u32) -> Label {
    Label {
        message: message.map(str::to_owned),
        start_line: 1,
        start_column: offset + 1,
        end_line: 1,
        end_column: offset + length + 1,
        offset,
        length,
    }
}
