import { createConfigForNuxt } from '@nuxt/eslint-config'

export default createConfigForNuxt({
  features: { tooling: true },
})
  .append({
    rules: { 'vue/multi-word-component-names': 'off' },
  })
  .append({
    // `app/components/ui/**` is generated by the shadcn-vue CLI — vendored library code we
    // do not hand-edit, so linting it only produces noise we are not allowed to fix.
    ignores: ['.nuxt/**', '.output/**', 'dist/**', 'app/lib/trestle-wasm/**', 'app/components/ui/**'],
  })
